spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret
---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  address: localhost

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
        # '[default_batch_fetch_size]': 100

logging:
  level:
    "[org.hibernate.SQL]": debug

boot:
  interval: 30
